spring:
  datasource:
    url: jdbc:mysql://203.245.44.84:3306/cnt89
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cnt89
    password: qaz@2wsx
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: false
    show-sql: true
    database: mysql
    open-in-view: true
    properties:
      hibernate.format_sql: true